DELETE FROM SEAT_RESERVATION;
DELETE FROM FARE;
DELETE FROM LEG_INSTANCE;
DELETE FROM FLIGHT_LEG;
DELETE FROM FLIGHT;
DELETE FROM AIRPORT;

DROP TABLE SEAT_RESERVATION;
DROP TABLE FARE;
DROP TABLE LEG_INSTANCE;
DROP TABLE FLIGHT_LEG;
DROP TABLE FLIGHT;
DROP TABLE AIRPORT;

SELECT * FROM cat;